Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,69 +7,68 @@ cache:
   - depends/built
   - depends/work
   - depends/sdk-sources
-  - "$HOME/.ccache"
+  - $HOME/.ccache
 env:
   global:
-  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-  - CCACHE_SIZE=200M
-  - CCACHE_TEMPDIR=/tmp/.ccache-temp
-  - CCACHE_COMPRESS=1
-  - MAKEJOBS="-j2"
-  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-  - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake
-    pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev
-    libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler
-    libqrencode-dev"
+    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+    - CCACHE_SIZE=200M
+    - CCACHE_TEMPDIR=/tmp/.ccache-temp
+    - CCACHE_COMPRESS=1
+    - MAKEJOBS="-j2"
+    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+    - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
   matrix:
-  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
-  - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
-  - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
-  - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
-  - HOST=x86_64-unknown-linux-gnu PACKAGES=""
-  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
-    libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
+# ARM32
+    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
+# ARM64
+    - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
+# Win32
+    - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
+# Win64
+    - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
+# x86_64 Linux
+    - HOST=x86_64-unknown-linux-gnu PACKAGES=""
+# Cross-Mac
+    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
+
 before_install:
-- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
-  sed "s|::|:|g")
+    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
 install:
-- sudo add-apt-repository -y ppa:bitcoin/bitcoin
-- sudo apt-get update
-- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
-- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
-  --no-upgrade -qq $PACKAGES; fi
+    - sudo add-apt-repository -y ppa:bitcoin/bitcoin
+    - sudo apt-get update
+    - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
+    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
 before_script:
-- unset CC; unset CXX
-- cd $TRAVIS_BUILD_DIR
-- mkdir -p depends/SDKs depends/sdk-sources
-- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
-  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
-  fi
-- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
-  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+    - unset CC; unset CXX
+    - cd $TRAVIS_BUILD_DIR
+    - mkdir -p depends/SDKs depends/sdk-sources
+    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
 script:
-- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-- |
-  ./build.sh
-  # Convert the timeout exit code to 0.
-  RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
+    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+    - |
+      timeout 1800 ./build.sh
+        # Convert the timeout exit code to 0.
+        RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
 before_deploy:
     - ./pre-deploy.sh
 deploy:
   - provider: releases
- api_key:		
- secure: k4O0gSel61utBgVv2JAet6VXgjIgWUI0GpKNy7zHXOS2DvE6nhOP9gm8mthLM6zWLUebRrfrLrjefO5sOS2HHoawA3z+tZf1Q2sF9TXOhWumtTvObqbXUHa3ZLZl3zPZQxAHBSn6Wai+mr7bAl6Ah1KyCv04B8xSn64koQnf8S+cMcULgi3XiaJJjcMS+247PPbVqcst6BC28ItmPkY55Shuif/sheK9A2lvv+QBtm1yohUrv1dYJGh5Ja96Y7H+WzII/oViB9ed3UpUdmYfVkq837OV4GbrTZHC2x4t6X5U6WN6xxCgAHd5LZL0/7fzikokNPyZUfAsWWHa/Fjxrz7CCFXepNHLQDmoe9ZoFWw9OyNczuausCQ7l3/KnfyhT1ruU4IKHS7KKAAkI+L+GBeKkv54LQW4ZX7MaV3SwdRN13FkbBqu5u+QlOVpYEEyBWC7G1vN2obPK4kdS4XDyStOEDdO57HD/eY+BYKvS3aFb6QkDQhJp2FFV8+S1OaQAYS8b0mEKcBuUBe6r1c+qOOXVILMpwiJoN29Wz8K/ZAUqwytsj+o9JpqT5Zwhf3cDUEwaoaIbtDT25Ci8JUUxRXxOAKzrtV+dNOYu27M07S9jbRK4TGXv0e0EyxDThJgWvODLjDWGPHBUW0YPbLnkAfE/idYwKEkjYTnNroSBjo=		      secure: k4O0gSel61utBgVv2JAet6VXgjIgWUI0GpKNy7zHXOS2DvE6nhOP9gm8mthLM6zWLUebRrfrLrjefO5sOS2HHoawA3z+tZf1Q2sF9TXOhWumtTvObqbXUHa3ZLZl3zPZQxAHBSn6Wai+mr7bAl6Ah1KyCv04B8xSn64koQnf8S+cMcULgi3XiaJJjcMS+247PPbVqcst6BC28ItmPkY55Shuif/sheK9A2lvv+QBtm1yohUrv1dYJGh5Ja96Y7H+WzII/oViB9ed3UpUdmYfVkq837OV4GbrTZHC2x4t6X5U6WN6xxCgAHd5LZL0/7fzikokNPyZUfAsWWHa/Fjxrz7CCFXepNHLQDmoe9ZoFWw9OyNczuausCQ7l3/KnfyhT1ruU4IKHS7KKAAkI+L+GBeKkv54LQW4ZX7MaV3SwdRN13FkbBqu5u+QlOVpYEEyBWC7G1vN2obPK4kdS4XDyStOEDdO57HD/eY+BYKvS3aFb6QkDQhJp2FFV8+S1OaQAYS8b0mEKcBuUBe6r1c+qOOXVILMpwiJoN29Wz8K/ZAUqwytsj+o9JpqT5Zwhf3cDUEwaoaIbtDT25Ci8JUUxRXxOAKzrtV+dNOYu27M07S9jbRK4TGXv0e0EyxDThJgWvODLjDWGPHBUW0YPbLnkAfE/idYwKEkjYTnNroSBjo=
- file: "out/**/zip/*"
- file_glob: true
- 
-
-deploy:
-  provider: s3
-  access_key_id: AKIAINKSHAFRY75DZNVA
-  secret_access_key:
-  secure: AyETnQvwBqCGzmLtJYMjmQLJGqD6pe1GzfTOiEBIaUnrrGtgzdPjwrZ2FJt0myywPqsIAJozcGgcVBtqgznMxBIXG/ApyZ1dGGFwRtHCyWV39jfgFyn7Fg9PSopmLim1fEmEttl2/WMA6K0NlAhkFXqem3WrhuWucYksRy1y7GP9R4BL7XQTRth+vBoBo9yWPCvv8Yb0vIDOianX8rxzByU+NG5t9LSF3t9CRaiyTdP9T+YyLGpzrZohafWrLo6HRoi1sSZvmFKuIlc+B5Wm1oYTkJAx8swb7iU5DAPtm6CBH7+qKhIQCgXSs+KlBORxKVjTpP5GoAKvvnBv5QNONeX9nqjjHYdPEGANLg+kRjLuT0nKxhynZpdvKdhvmljEL4kjfQneh9mQcgcA3CaF3tu9yn9ZW4yqizM+DUGZFUfr6z2nYO5jsad7fCQ3QO+WdfpZkVdhCSlA4HTysq54dwAaKisLn2gXnrip7OiVWMaQqY2Cw4p/ke1+45CdMgv1D4gWMonr58guBtHz+Xwvyo3ANl/5hgLroZLVJRuM/nBI1ma8CwHFymioEblFhTB6InR+JTHCOyENOTl9GT0RAEvbl9MjecfGLGHa8z6Kc5knBYxSxB1k+SWB6LwmVDrFUP4bXnNEs3FTMPBYc9o5wZ20GBTccEh+XFRGX7qv8I8=
-  bucket: rupaya
-  acl: public_read
-  upload_dir: $TRAVIS_JOB_NUMBER
-  cache_control: "max-age=21600"
-  on:
+    api_key:
+    secure: k4O0gSel61utBgVv2JAet6VXgjIgWUI0GpKNy7zHXOS2DvE6nhOP9gm8mthLM6zWLUebRrfrLrjefO5sOS2HHoawA3z+tZf1Q2sF9TXOhWumtTvObqbXUHa3ZLZl3zPZQxAHBSn6Wai+mr7bAl6Ah1KyCv04B8xSn64koQnf8S+cMcULgi3XiaJJjcMS+247PPbVqcst6BC28ItmPkY55Shuif/sheK9A2lvv+QBtm1yohUrv1dYJGh5Ja96Y7H+WzII/oViB9ed3UpUdmYfVkq837OV4GbrTZHC2x4t6X5U6WN6xxCgAHd5LZL0/7fzikokNPyZUfAsWWHa/Fjxrz7CCFXepNHLQDmoe9ZoFWw9OyNczuausCQ7l3/KnfyhT1ruU4IKHS7KKAAkI+L+GBeKkv54LQW4ZX7MaV3SwdRN13FkbBqu5u+QlOVpYEEyBWC7G1vN2obPK4kdS4XDyStOEDdO57HD/eY+BYKvS3aFb6QkDQhJp2FFV8+S1OaQAYS8b0mEKcBuUBe6r1c+qOOXVILMpwiJoN29Wz8K/ZAUqwytsj+o9JpqT5Zwhf3cDUEwaoaIbtDT25Ci8JUUxRXxOAKzrtV+dNOYu27M07S9jbRK4TGXv0e0EyxDThJgWvODLjDWGPHBUW0YPbLnkAfE/idYwKEkjYTnNroSBjo=		      secure: k4O0gSel61utBgVv2JAet6VXgjIgWUI0GpKNy7zHXOS2DvE6nhOP9gm8mthLM6zWLUebRrfrLrjefO5sOS2HHoawA3z+tZf1Q2sF9TXOhWumtTvObqbXUHa3ZLZl3zPZQxAHBSn6Wai+mr7bAl6Ah1KyCv04B8xSn64koQnf8S+cMcULgi3XiaJJjcMS+247PPbVqcst6BC28ItmPkY55Shuif/sheK9A2lvv+QBtm1yohUrv1dYJGh5Ja96Y7H+WzII/oViB9ed3UpUdmYfVkq837OV4GbrTZHC2x4t6X5U6WN6xxCgAHd5LZL0/7fzikokNPyZUfAsWWHa/Fjxrz7CCFXepNHLQDmoe9ZoFWw9OyNczuausCQ7l3/KnfyhT1ruU4IKHS7KKAAkI+L+GBeKkv54LQW4ZX7MaV3SwdRN13FkbBqu5u+QlOVpYEEyBWC7G1vN2obPK4kdS4XDyStOEDdO57HD/eY+BYKvS3aFb6QkDQhJp2FFV8+S1OaQAYS8b0mEKcBuUBe6r1c+qOOXVILMpwiJoN29Wz8K/ZAUqwytsj+o9JpqT5Zwhf3cDUEwaoaIbtDT25Ci8JUUxRXxOAKzrtV+dNOYu27M07S9jbRK4TGXv0e0EyxDThJgWvODLjDWGPHBUW0YPbLnkAfE/idYwKEkjYTnNroSBjo=
+    file_glob: true
+    file: out/**/zip/*
+    skip_cleanup: true
+    on:
+      tags: true
+  - provider: s3
+    access_key_id: AKIAINKSHAFRY75DZNVA
+    secret_access_key:
+    secure: AyETnQvwBqCGzmLtJYMjmQLJGqD6pe1GzfTOiEBIaUnrrGtgzdPjwrZ2FJt0myywPqsIAJozcGgcVBtqgznMxBIXG/ApyZ1dGGFwRtHCyWV39jfgFyn7Fg9PSopmLim1fEmEttl2/WMA6K0NlAhkFXqem3WrhuWucYksRy1y7GP9R4BL7XQTRth+vBoBo9yWPCvv8Yb0vIDOianX8rxzByU+NG5t9LSF3t9CRaiyTdP9T+YyLGpzrZohafWrLo6HRoi1sSZvmFKuIlc+B5Wm1oYTkJAx8swb7iU5DAPtm6CBH7+qKhIQCgXSs+KlBORxKVjTpP5GoAKvvnBv5QNONeX9nqjjHYdPEGANLg+kRjLuT0nKxhynZpdvKdhvmljEL4kjfQneh9mQcgcA3CaF3tu9yn9ZW4yqizM+DUGZFUfr6z2nYO5jsad7fCQ3QO+WdfpZkVdhCSlA4HTysq54dwAaKisLn2gXnrip7OiVWMaQqY2Cw4p/ke1+45CdMgv1D4gWMonr58guBtHz+Xwvyo3ANl/5hgLroZLVJRuM/nBI1ma8CwHFymioEblFhTB6InR+JTHCOyENOTl9GT0RAEvbl9MjecfGLGHa8z6Kc5knBYxSxB1k+SWB6LwmVDrFUP4bXnNEs3FTMPBYc9o5wZ20GBTccEh+XFRGX7qv8I8=
+    bucket: rupaya
+    skip_cleanup: true
+    acl: public_read
+    upload_dir: $TRAVIS_JOB_NUMBER
+    cache_control: "max-age=21600"
+    on:
       all_branches: true
