added releases

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,68 +7,57 @@ cache:
   - depends/built
   - depends/work
   - depends/sdk-sources
-  - $HOME/.ccache
+  - "$HOME/.ccache"
 env:
   global:
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - CCACHE_SIZE=200M
-    - CCACHE_TEMPDIR=/tmp/.ccache-temp
-    - CCACHE_COMPRESS=1
-    - MAKEJOBS="-j2"
-    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
+  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+  - CCACHE_SIZE=200M
+  - CCACHE_TEMPDIR=/tmp/.ccache-temp
+  - CCACHE_COMPRESS=1
+  - MAKEJOBS="-j2"
+  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+  - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake
+    pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev
+    libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler
+    libqrencode-dev"
   matrix:
-# ARM32
-    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
-# ARM64
-    - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
-# Win32
-    - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
-# Win64
-    - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
-# x86_64 Linux
-    - HOST=x86_64-unknown-linux-gnu PACKAGES=""
-# Cross-Mac
-    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
-
+  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
+  - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
+  - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
+  - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
+  - HOST=x86_64-unknown-linux-gnu PACKAGES=""
+  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
 before_install:
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
-    - sudo add-apt-repository -y ppa:bitcoin/bitcoin
-    - sudo apt-get update
-    - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- sudo add-apt-repository -y ppa:bitcoin/bitcoin
+- sudo apt-get update
+- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
-    - unset CC; unset CXX
-    - cd $TRAVIS_BUILD_DIR
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+- unset CC; unset CXX
+- cd $TRAVIS_BUILD_DIR
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
 script:
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - |
-        ./build.sh
-        # Convert the timeout exit code to 0.
-        RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
+- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
+- |
+  ./build.sh
+  # Convert the timeout exit code to 0.
+  RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
 before_deploy:
-    - ./pre-deploy.sh
+- "./pre-deploy.sh"
 deploy:
-  - provider: releases
-    api_key:
-      secure: gYnYhwzJJpnAB8kyjB+KseEULdmnB2cnNv447jQ+hH2lcX5jA7UHW5U8hv7xf8HA4Brv9VMQuj+ZX8P5bgm5oU7AJ9Y/nMrO8HJV2dguE/zWoXhvMOMRd7CC88PMVg7LT1zvCot2p5np0nEOinx5qjPp8K9/t+hSWXHsPCX2kA+VDmPSkQ+6L8ih7zO2lW66BKg3rbKiDfBtnT25wTcVPFEdxAuZYiX+kE3q9ei41rKE1+ibj+8wZOxhyJLPi3kBsOsNuybWlZbMVYCpSIukd24+GugFYx4eQBZ7AH9sb8v4kifV8rl5ru43CxaD/ub634RN8UlbNikvPZffDJqoWPfRnpoJyZpCc8XDM0yKyeZaWvdk8zq2UchRB03sxHAuXteQgMQU/tUdDW+kDBKL3WLx2ut2LK/bfD/JHQ9GbZjfRE4L+NbA/hQRJiz6FHMmbp+kY5pH9w9NeL9HOpR6faxA8aCSAvXQFugY+vk4LmJ//d775E9ba/8OfMoXk3RwUvfCOop+iz1Qpul658JvDoBlon6qSBcPZmMq4wG/3v7J/jdB7RKezb8YzeYqKEoF9o2bs1kuXDmk/snblcODbQ/PK8Toes6XJHsCu8UZrlOXT7TBF7DtD9/O7bYB/TRVgyXWCJyfUYOlWmQBBz6Do7/SOp0oFgkJoAS/fJBYZSA=
-    file_glob: true
-    file: out/**/zip/*
-    skip_cleanup: true
-    on:
-      tags: true
-#   - provider: s3
-#     access_key_id: $ARTIFACTS_KEY
-#     secret_access_key: $ARTIFACTS_SECRET
-#     bucket: $ARTIFACTS_BUCKET
-#     skip_cleanup: true
-#     acl: public_read
-#     local_dir: $OUTDIR/*
-#     upload_dir: $TRAVIS_JOB_NUMBER
-#     cache_control: "max-age=21600"
-#     on:
-#       all_branches: true
+  provider: releases
+  api_key:
+    secure: k4O0gSel61utBgVv2JAet6VXgjIgWUI0GpKNy7zHXOS2DvE6nhOP9gm8mthLM6zWLUebRrfrLrjefO5sOS2HHoawA3z+tZf1Q2sF9TXOhWumtTvObqbXUHa3ZLZl3zPZQxAHBSn6Wai+mr7bAl6Ah1KyCv04B8xSn64koQnf8S+cMcULgi3XiaJJjcMS+247PPbVqcst6BC28ItmPkY55Shuif/sheK9A2lvv+QBtm1yohUrv1dYJGh5Ja96Y7H+WzII/oViB9ed3UpUdmYfVkq837OV4GbrTZHC2x4t6X5U6WN6xxCgAHd5LZL0/7fzikokNPyZUfAsWWHa/Fjxrz7CCFXepNHLQDmoe9ZoFWw9OyNczuausCQ7l3/KnfyhT1ruU4IKHS7KKAAkI+L+GBeKkv54LQW4ZX7MaV3SwdRN13FkbBqu5u+QlOVpYEEyBWC7G1vN2obPK4kdS4XDyStOEDdO57HD/eY+BYKvS3aFb6QkDQhJp2FFV8+S1OaQAYS8b0mEKcBuUBe6r1c+qOOXVILMpwiJoN29Wz8K/ZAUqwytsj+o9JpqT5Zwhf3cDUEwaoaIbtDT25Ci8JUUxRXxOAKzrtV+dNOYu27M07S9jbRK4TGXv0e0EyxDThJgWvODLjDWGPHBUW0YPbLnkAfE/idYwKEkjYTnNroSBjo=
+  file: "out/**/zip/*"
+  on:
+    repo: rupaya-project/rupaya
